name: xylophone
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  audiofileplayer: ^2.1.1
#  audioplayers: ^4.1.0
#  assets_audio_player: ^3.0.6
  # Use Audioplayers dependency version 0.17.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:

  uses-material-design: true

  assets:
    - assets/

